version: "3"

services:
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: custom_phpmyadmin
      links:
          - mariadb:db
          - mariadb:mysql
      ports:
          - "8888:80"
